### ISSUE TITLE
Keymap diagram omits "<" & ">"

### ISSUE THREAD

**Issue by JohnMasinter** [yumagulovrn/dao-zmk-config#27]
Keymap diagram omits "<" & ">". This was frustrating until I found it by experimentation. It was right where it is usually found, default layer, shift over comma and period. Thank you to yumagulovrn for this terrific keyboard!

**Comment by yumagulovrn** [comment]
Hey mate!

Good job on finding them. I've changed the diagrams to properly reflect "<" and ">". Thanks for the feedback!
