### ISSUE TITLE
West Build Error (dao_left)

### ISSUE THREAD

**Issue by dosamine** [yumagulovrn/dao-zmk-config#6]
Receiving a west build error for only the left half of the dao keyboard when changing the keymap and building new firmware. Only the left half seems not to work, everything else builds properly. Maybe an issue with `ZMK_SPLIT_BLE_ROLE_CENTRAL` in the split bluetooth kconfig.

**Comment by yumagulovrn** [comment]
Hi! I'll look into it today

**Comment by yumagulovrn** [comment]
Fixed in #5

Thank you for the reminder!
